// <auto-generated />
using System;
using Barnabas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barnabas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BarnabasDbContext))]
    [Migration("20260906160511_Notifications")]
    partial class Notifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Barnabas.Domain.Access.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Access.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Access.SignInToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("SignInTokens", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Congregations.Congregation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HelpTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Neighbourhoods")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Congregations_Slug");

                    b.ToTable("Congregations", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Congregations.InviteCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("IssuedByMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InviteCodes", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Congregations.JoiningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InviteCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("JoiningSessions", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Listings.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ClosedOutAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Neighbourhood")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CongregationId", "Status", "PostedAt");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Neighbourhood")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReasonForJoining")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CongregationId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("CongregationId", "Status", "DisplayName");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Messaging.MessageThread", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("RequesterId");

                    b.ToTable("MessageThreads", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Messaging.ThreadReadMark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "MemberId")
                        .IsUnique();

                    b.ToTable("ThreadReadMarks", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ListingTitle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectMemberDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("SubjectMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("IX_Notifications_Unread")
                        .HasFilter("[ReadAt] IS NULL");

                    b.HasIndex("RecipientId", "CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.HasKey("MemberId", "Kind");

                    b.ToTable("NotificationPreferences", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Requests.ListingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("MadeAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ListingId", "RequesterId")
                        .IsUnique()
                        .HasDatabaseName("IX_ListingRequests_OneOpenRequestPerMember")
                        .HasFilter("[Status] = 0");

                    b.HasIndex("ListingId", "Status");

                    b.ToTable("ListingRequests", (string)null);
                });

            modelBuilder.Entity("Barnabas.Domain.Listings.Listing", b =>
                {
                    b.OwnsMany("Barnabas.Domain.Listings.AvailabilityWindow", "AvailabilityWindows", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Day")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("EndsAt")
                                .HasColumnType("time");

                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeOnly>("StartsAt")
                                .HasColumnType("time");

                            b1.HasKey("Id");

                            b1.HasIndex("ListingId");

                            b1.ToTable("AvailabilityWindows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Barnabas.Domain.Listings.LoanTerms", "LoanTerms", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("ReturnBy")
                                .HasColumnType("date")
                                .HasColumnName("ReturnBy");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("AvailabilityWindows");

                    b.Navigation("LoanTerms");
                });

            modelBuilder.Entity("Barnabas.Domain.Members.Member", b =>
                {
                    b.OwnsMany("Barnabas.Domain.Members.MemberHelpTag", "HelpTags", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Tag")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("MemberId", "Tag");

                            b1.HasIndex("Tag");

                            b1.ToTable("MemberHelpTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("HelpTags");
                });

            modelBuilder.Entity("Barnabas.Domain.Messaging.Message", b =>
                {
                    b.HasOne("Barnabas.Domain.Messaging.MessageThread", null)
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Barnabas.Domain.Messaging.ThreadReadMark", b =>
                {
                    b.HasOne("Barnabas.Domain.Messaging.MessageThread", null)
                        .WithMany("ReadMarks")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Barnabas.Domain.Requests.ListingRequest", b =>
                {
                    b.OwnsOne("Barnabas.Domain.Requests.HelpRequestTerms", "HelpTerms", b1 =>
                        {
                            b1.Property<Guid>("ListingRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AvailabilityWindowId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AvailabilityWindowId");

                            b1.HasKey("ListingRequestId");

                            b1.ToTable("ListingRequests");

                            b1.WithOwner()
                                .HasForeignKey("ListingRequestId");
                        });

                    b.OwnsOne("Barnabas.Domain.Requests.LoanRequestTerms", "LoanTerms", b1 =>
                        {
                            b1.Property<Guid>("ListingRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("PickupOn")
                                .HasColumnType("date")
                                .HasColumnName("PickupOn");

                            b1.Property<DateOnly>("ReturnBy")
                                .HasColumnType("date")
                                .HasColumnName("RequestedReturnBy");

                            b1.HasKey("ListingRequestId");

                            b1.ToTable("ListingRequests");

                            b1.WithOwner()
                                .HasForeignKey("ListingRequestId");
                        });

                    b.OwnsOne("Barnabas.Domain.Requests.PickupRequestTerms", "PickupTerms", b1 =>
                        {
                            b1.Property<Guid>("ListingRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("PickupAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("PickupAt");

                            b1.HasKey("ListingRequestId");

                            b1.ToTable("ListingRequests");

                            b1.WithOwner()
                                .HasForeignKey("ListingRequestId");
                        });

                    b.Navigation("HelpTerms");

                    b.Navigation("LoanTerms");

                    b.Navigation("PickupTerms");
                });

            modelBuilder.Entity("Barnabas.Domain.Messaging.MessageThread", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ReadMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
